#!/bin/bash

case `id` in
*root*)
        ;;
*)
        exec echo Must be run as root
        ;;
esac

chruby_version=0.3.9
chruby=chruby-${chruby_version}

set -xe
id
pwd
export DEBIAN_FRONTEND=noninteractive
find /tmp/got-apt-update -mtime -1 || ( apt-get update && touch /tmp/got-apt-update )
apt install --yes --force-yes -q ruby ruby-dev sqlite3 libsqlite3-dev nodejs subversion git git-core
# https://github.com/rbenv/ruby-build/wiki#suggested-build-environment
# using default gcc-5 since xenial doesn't have gcc-6
apt install --yes --force-yes -q gcc-5 autoconf bison build-essential libssl-dev libyaml-dev libreadline6-dev zlib1g-dev libncurses5-dev libffi-dev libgdbm3 libgdbm-dev

# The following is not required for testing, install if you are doing manual tests with extra gems
# apt install --yes --force-yes -q mysql-client mysql-server libmysqlclient-dev
# apt install --yes --force-yes -q libcurl4-openssl-dev libncurses5-dev libxml2-dev libxslt1-dev
(
  echo Install chruby
  [ -s ${chruby}.tar.gz ] || wget -q -O ${chruby}.tar.gz https://github.com/postmodern/chruby/archive/v${chruby_version}.tar.gz
  [ -d ${chruby} ] || tar -xzf ${chruby}.tar.gz
  cd ${chruby}/
  ./scripts/setup.sh
  cat > /etc/profile.d/chruby.sh <<'EOF'
if [ -n "$BASH_VERSION" ] || [ -n "$ZSH_VERSION" ]; then
  source /usr/local/share/chruby/chruby.sh
  #source /usr/local/share/chruby/auto
fi
EOF
  chmod a+r /etc/profile.d/chruby.sh
)

(
  [ -d ruby-build ] || git clone https://github.com/rbenv/ruby-build.git
  which ruby-build || PREFIX=/usr/local ./ruby-build/install.sh

  mkdir -p /opt/rubies
  v=1.8.7-p375
  [ -x /opt/rubies/${v}/bin/bundle ] || ( ruby-build ${v} /opt/rubies/${v} && /opt/rubies/${v}/bin/gem update --system 1.8.25 && /opt/rubies/${v}/bin/gem install bundler )
    
  v=1.9.3-p551
  [ -x /opt/rubies/${v}/bin/bundle ] || ( ruby-build ${v} /opt/rubies/${v} && /opt/rubies/${v}/bin/gem install bundler )

  for v in 2.2.0
  do
    [ -x /opt/rubies/${v}/bin/bundle ] || ( ruby-build ${v} /opt/rubies/${v} && /opt/rubies/${v}/bin/gem install bundler )
  done
)

echo Setup system ruby
which bundle || gem install bundler 
bundle --version
set +x
cat <<EOF

Now test by running the following commands:

  vagrant ssh
  cd /vagrant

  chruby RUBY_VERSION
  or
  chruby system # for system version 2.3.1

  ./test/test_with_railsapp

  exit

EOF
exit
