# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{health_check}
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Ian Heggie"]
  s.date = %q{2010-01-29}
  s.description = %q{Simple health check of Rails app for use with uptime.openacs.org or wasitup.com}
  s.email = %q{ian@heggie.biz}
  s.extra_rdoc_files = [
    "README.rdoc"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "MIT-LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "health_check.gemspec",
     "init.rb",
     "lib/health_check.rb",
     "lib/health_check/add_routes.rb",
     "lib/health_check/health_check_class.rb",
     "lib/health_check/health_check_controller.rb",
     "test/helper.rb",
     "test/migrate/empty/do_not_remove.txt",
     "test/migrate/twelve/012_create_users.rb",
     "test/migrate/twelve/9_create_countries.rb",
     "test/test_health_check_controller.rb",
     "test/test_routes.rb"
  ]
  s.homepage = %q{http://github.com/ianheggie/health_check}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{Simple health check of Rails app}
  s.test_files = [
    "test/helper.rb",
     "test/migrate/twelve/012_create_users.rb",
     "test/migrate/twelve/9_create_countries.rb",
     "test/test_health_check_controller.rb",
     "test/test_routes.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<shoulda>, [">= 0"])
      s.add_development_dependency(%q<sqlite3-ruby>, [">= 0"])
      s.add_development_dependency(%q<activerecord>, [">= 1.15.4.7794"])
    else
      s.add_dependency(%q<shoulda>, [">= 0"])
      s.add_dependency(%q<sqlite3-ruby>, [">= 0"])
      s.add_dependency(%q<activerecord>, [">= 1.15.4.7794"])
    end
  else
    s.add_dependency(%q<shoulda>, [">= 0"])
    s.add_dependency(%q<sqlite3-ruby>, [">= 0"])
    s.add_dependency(%q<activerecord>, [">= 1.15.4.7794"])
  end
end

